services:
  - type: web
    name: priyansh-portfolio
    runtime: node
    plan: free
    repo: https://github.com/Dev-Divyansh-code/priyansh-portfolio
    branch: main
    buildCommand: npm run install:all && npm run build
    startCommand: npm run start --prefix server
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: ADMIN_API_KEY
        generateValue: true
      - key: CLIENT_URL
        sync: false